use bevy::prelude::*;
use bevy::render::extract_resource::{ExtractResource, ExtractResourcePlugin};
use bevy::render::render_resource::*;
use bevy::shader::ShaderRef;

// polars is only used in the test module and in other crates that import flan's
// polars-based types, when I add more plot shaders it'll come back with a
// vengeance methinks.
//
// The whole goal of this shader lib is to bolt polars onto shaders directly
// transparently for crap like plot shaders. I have a better idea on how I'll do
// that, think I'll just bolt a message onto a wrapper fn for updating the
// dataframe that lets the render subsystem to update the storage buffer or
// texture yeeting data betwixt the dataframe and the shader. Then any user land
// code is just: update the Component dataframe and tag it as dirty and then
// flan can take care of updating the underlying data and you're at most 2-3
// frames away from seeing an update in your gooey.
#[cfg(not(target_arch = "wasm32"))]
#[allow(unused_imports)]
use polars::prelude::*;

#[cfg(not(feature = "webgl"))]
use bevy::{
    asset::RenderAssetUsages,
    render::{
        Render, RenderApp, RenderSystems,
        render_asset::RenderAssets,
        renderer::RenderQueue,
        storage::{GpuShaderBuffer, ShaderBuffer},
    },
};

pub mod layout;
pub mod post_process;
/// Typst layout engine integration for feature = "typst".
///
/// Named `slug_typst` to avoid ambiguity with the `typst` external crate.
#[cfg(feature = "typst")]
#[path = "typst/mod.rs"]
pub mod slug_typst;

/// Bevy component + plugin for typst-sourced text rendering (feature = "typst").
#[cfg(feature = "typst")]
pub mod typst_text;
pub use post_process::{
    ActiveShader, AvailableShaders, EffectsEnabled, PostProcessPlugin, PostProcessSettings,
    ShaderInfo,
};
pub mod shaders;
pub mod slug_text;
pub mod slug_text_material;
pub mod stats;
pub mod text3d;
pub mod text3d_font;

pub use layout::{Horizontal, Layout, Vertical};
pub use slug_text::{
    ExtraGlyphNeeds, SlugAtlasSet, SlugPlugin, SlugTextFont, SlugTextMesh, SlugTextNode,
    Text3dDirty, build_mesh_from_run, normalize_run_3d,
};
#[cfg(not(feature = "webgl"))]
pub use slug_text_material::{SlugAtlasBuffers, SlugText3dMaterial, SlugTextMaterial};
pub use slug_text_material::{
    SlugAtlasImages, SlugText3dTextureMaterial, SlugTextMaterialPlugin, SlugTextTextureMaterial,
};
pub use stats::overlay::{
    StatsOverlayHandle, StatsOverlayMaterial, StatsOverlayMaterialPlugin, StatsOverlayParams,
    StatsOverlayTextureMaterial, build_fps_points_image,
};
pub use text3d::{
    ShowText3d, SlugText3dApply, SlugText3dFontValidation, SlugText3dPlugin, SlugText3dState,
    SlugTextAnchor, Text3d, Text3dRenderer, spawn_text3d,
};
pub use text3d_font::Text3dFontId;

pub mod wesl;

/// Selects which GPU data path a shader uses. I want this to be mostly
/// transparent betwixt stupid, dum, annoying, makes me angy, seems to be the
/// most annoying technology ever, webgl2 and basically every other shader type
/// in existence. I can't wait to drop the texture paths for webgl2.
///
/// - `Default` = native / WebGPU path: data lives in storage buffers. This
///   is what you want on desktop, native mobile, and WebGPU targets.
/// - `Texture` = WebGL-compatible path: data is packed into 2-D `rgba32`
///   data textures and read with `textureLoad`. Use this on WebGL2.
///
/// Both variants are always compiled; callers pick the right one at runtime.
/// There are no `#[cfg(feature = "webgl")]` gates on individual types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum ShaderVariant {
    #[default]
    Default,
    Texture,
}

/// Shared test infrastructure for uniform structs, data helpers, and
/// backend-specific render helpers for the custom wgpu renderer and pseudo bevy
/// shader infra.
///
/// Exposed as a library so integration test binaries can import directly from
/// `flan::test::lib::*` `flan::test::lib::wgpu::*` instead of copy/pasta all over.
pub mod test;

/// Slug font atlas builder is mostly just TTF/OTF curve data to GPU curve/band
/// buffers for the Slug renderer to work. Uses ttf-parser and bytemuck for the
/// evil.
pub mod slug;

/// Glyph extrusion to build side-wall geometry from flan slug bezier contours
/// to replace prior bevy-fontmeash usage so I don't have holes all over in
/// kanji glyphs. I got other problems but 99 filled in holes isn't one now.
pub mod extrude;
pub use extrude::build_text_3d_mesh;
pub use slug::OutlineType;

// TODO: This is all a bit of a carry over of stupid approaches I took in the past.
//
// This all needs a general refactor "real soon now". Mostly need to brain a bit
// on making this stuff generic across different shaders. I mostly copy/pasted
// everything around without much concern to the design. But now that I've
// started abusing it I can see where the shape of an api might be to start with.

// Constants generated by build.rs for all the macro bs.
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

/// Marker component so the animation system can find the spawned plot UI node.
#[derive(Component)]
pub struct PlotUiNode;

/// Marker component for an fps sparkline plot, abusing flan for this idea to
/// benchmark crap and test out my first idea at an api. I need to read more
/// Bevy apps to see if this is good or bad.
///
/// Callers spawn a `MaterialNode<PlotUiMaterial>` with this component attached
/// and place it wherever they want. `flan` will sync data from
/// `SparklineDataFrame` to every entity carrying this marker. All we do here
/// is populate the dataframe with data.
// TODO: Ressurect this when I start adding more plot style shaders to flan.
#[derive(Component)]
pub struct SparklineUiNode;

/// Raw bytes to upload to the sparkline GPU storage buffer each ECS tick if
/// data changes.
///
/// The consumer fills this with `vec2<f32>` data at 8 bytes per point, x then y
/// as little-endian f32. flan's render-world `upload_sparkline` system calls
/// `write_buffer` on the pre-allocated GPU buffer so we don't leak bind group
/// buffers in wgpu.
///
// TODO: This whole system needs a rethink as my approach before leaked bind
// groups like mad. I need to come up with a more opaque api for all these
// shaders that hides all this nonsense. But I can't think of a good one so I'll
// leave it to future sucker mitch.
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct SparklineUpload {
    pub bytes: Vec<u8>,
}

/// Handle to the pre-allocated `ShaderStorageBuffer`.
///
/// Set once by the consumer's sparkline setup system. The pre-allocated buffer
/// must be created with `STORAGE | COPY_DST` usage so that the render-world
/// `write_buffer` calls succeed.
///
// This whole things begging to be a callback the consumer calls and we use in
// the struct impl somewhere. Or likely a struct field to yeet this out of the
// ECS directly where it isn't all that useful.
#[cfg(not(feature = "webgl"))]
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct SparklineBufferHandle(pub Option<Handle<ShaderBuffer>>);

/// Raw bytes to upload to the line-graph plot GPU storage buffer each tick.
///
/// Same contract as `SparklineUpload` - tightly-packed `vec2<f32>` bytes.
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct PlotUpload {
    pub bytes: Vec<u8>,
}

/// Handle to the line-graph plot `ShaderStorageBuffer`.
#[cfg(not(feature = "webgl"))]
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct PlotBufferHandle(pub Option<Handle<ShaderBuffer>>);

pub struct PlotPlugin;

impl Plugin for PlotPlugin {
    fn build(&self, app: &mut App) {
        // ShadersPlugin must already have been added by the consuming app.
        #[cfg(not(feature = "webgl"))]
        app.add_plugins(UiMaterialPlugin::<PlotUiMaterial>::default());
        app.add_plugins(UiMaterialPlugin::<PlotUiMaterialTexture>::default())
            .add_systems(Startup, setup_plot_ui)
            // ExtractResource pipelines for the upload byte buffers and
            // stable buffer handles. These flow main-world to render-world
            // every frame so shader upload systems always have the latest data.
            .add_plugins(ExtractResourcePlugin::<SparklineUpload>::default())
            .add_plugins(ExtractResourcePlugin::<PlotUpload>::default())
            .init_resource::<SparklineUpload>()
            .init_resource::<PlotUpload>();

        #[cfg(not(feature = "webgl"))]
        app.add_plugins(ExtractResourcePlugin::<SparklineBufferHandle>::default())
            .add_plugins(ExtractResourcePlugin::<PlotBufferHandle>::default())
            .init_resource::<SparklineBufferHandle>()
            .init_resource::<PlotBufferHandle>();

        #[cfg(not(feature = "webgl"))]
        if let Some(render_app) = app.get_sub_app_mut(RenderApp) {
            render_app.add_systems(
                Render,
                (upload_sparkline, upload_plot).in_set(RenderSystems::Queue),
            );
        }
    }
}

/// Render-world system to write sparkline bytes into the GPU buffer. Runs in
/// RenderSet::Queue so these bytes are on the GPU before the render pass
/// begins.
#[cfg(not(feature = "webgl"))]
fn upload_sparkline(
    upload: Res<SparklineUpload>,
    handle: Res<SparklineBufferHandle>,
    gpu_bufs: Res<RenderAssets<GpuShaderBuffer>>,
    render_queue: Res<RenderQueue>,
) {
    if let (Some(h), false) = (&handle.0, upload.bytes.is_empty())
        && let Some(gpu_buf) = gpu_bufs.get(h.id())
    {
        render_queue.write_buffer(&gpu_buf.buffer, 0, &upload.bytes);
    }
}

/// Render-world system to write plot bytes into the GPU buffer.
#[cfg(not(feature = "webgl"))]
fn upload_plot(
    upload: Res<PlotUpload>,
    handle: Res<PlotBufferHandle>,
    gpu_bufs: Res<RenderAssets<GpuShaderBuffer>>,
    render_queue: Res<RenderQueue>,
) {
    if let (Some(h), false) = (&handle.0, upload.bytes.is_empty())
        && let Some(gpu_buf) = gpu_bufs.get(h.id())
    {
        render_queue.write_buffer(&gpu_buf.buffer, 0, &upload.bytes);
    }
}

/// Setup the plot UI node.
#[cfg(not(feature = "webgl"))]
fn setup_plot_ui(
    mut commands: Commands,
    mut ui_materials: ResMut<Assets<PlotUiMaterial>>,
    mut buffers: ResMut<Assets<ShaderBuffer>>,
) {
    let zeros = vec![0u8; MAX_PLOT_POINTS * 8];
    let mut buf = ShaderBuffer::new(&zeros, RenderAssetUsages::RENDER_WORLD);
    buf.buffer_description.usage = BufferUsages::STORAGE | BufferUsages::COPY_DST;
    let points_handle = buffers.add(buf);
    commands.insert_resource(PlotBufferHandle(Some(points_handle.clone())));

    let material = ui_materials.add(PlotUiMaterial {
        params: PlotUniform {
            min: Vec2::ZERO,
            max: Vec2::ONE,
            zoom: Vec2::ONE,
            offset: Vec2::ZERO,
            count: 0,
            line_width: 0.003,
            _pad: 0.000,
        },
        points: points_handle,
    });

    commands.spawn((
        Node {
            position_type: PositionType::Absolute,
            left: Val::Px(10.0),
            // Keep this vertically centered so that top 50% minus half the
            // widget height. TODO: This is for the singleton currently in use,
            // this all needs to become more dynamic and let me have the ability
            // to spawn multiple Nodes in aggregate for more complex layouts.
            top: Val::Percent(50.0),
            margin: UiRect {
                top: Val::Px(-100.0),
                ..default()
            },
            width: Val::Px(200.0),
            height: Val::Px(200.0),
            ..default()
        },
        Visibility::Hidden,
        MaterialNode(material),
        PlotUiNode,
    ));
}

/// Setup the plot UIMaterial node as a texture flavor.
#[cfg(feature = "webgl")]
fn setup_plot_ui(mut commands: Commands, mut ui_materials: ResMut<Assets<PlotUiMaterialTexture>>) {
    let material = ui_materials.add(PlotUiMaterialTexture {
        params: PlotUniform {
            min: Vec2::ZERO,
            max: Vec2::ONE,
            zoom: Vec2::ONE,
            offset: Vec2::ZERO,
            count: 0,
            line_width: 0.003,
            _pad: 0.000,
        },
        points: PlotPointsUniform {
            data: [Vec4::ZERO; MAX_PLOT_POINTS],
        },
    });

    commands.spawn((
        Node {
            position_type: PositionType::Absolute,
            left: Val::Px(10.0),
            top: Val::Percent(50.0),
            margin: UiRect {
                top: Val::Px(-100.0),
                ..default()
            },
            width: Val::Px(200.0),
            height: Val::Px(200.0),
            ..default()
        },
        Visibility::Hidden,
        MaterialNode(material),
        PlotUiNode,
    ));
}

/// Uniform data shared between the Rust side and every plot shader variant.
///
/// `count` is only consumed by the WEBGL path (the storage-buffer path uses
/// `arrayLength` instead), but it is always present so the WGSL struct layout
/// is identical across all variants.
///
/// 48 bytes to fit STD140 requirements. I punted on the padding of the struct a
// bit. TODO: I was abusing bytemuck for this but explore using the bevy
// approach for auto padding this commits crazy as it is.
#[derive(Clone, Copy, ShaderType)]
pub struct PlotUniform {
    pub min: Vec2,
    pub max: Vec2,
    pub zoom: Vec2,
    pub offset: Vec2,
    pub count: u32,
    // pad to 48 bytes for webgl bs
    pub _pad: f32,
    /// Antialiased half-width of the polyline in UV space. 16 byte aligned for webgl
    #[shader(size(8))]
    pub line_width: f32,
}

/// Points buffer for the texture (WebGL2-compatible) plot shader variant.
///
/// Uses `Vec4` so the Rust layout and the WGSL `array<vec4<f32>, MAX_PLOT_POINTS>`
/// layout agree exactly under std140. The `.xy` components hold `(x, y)` data;
/// `.zw` are zero-padded.
#[derive(Clone, ShaderType)]
pub struct PlotPointsUniform {
    pub data: [Vec4; MAX_PLOT_POINTS],
}

/// Plot `UiMaterial` - native / WebGPU path.
///
/// Points live in a `ShaderBuffer` at `@group(1) @binding(1)`.
#[cfg(not(feature = "webgl"))]
#[derive(Asset, AsBindGroup, TypePath, Clone)]
pub struct PlotUiMaterial {
    #[uniform(0)]
    pub params: PlotUniform,
    #[storage(1, read_only)]
    pub points: Handle<ShaderBuffer>,
}

#[cfg(not(feature = "webgl"))]
impl UiMaterial for PlotUiMaterial {
    fn fragment_shader() -> ShaderRef {
        ShaderRef::Handle(shaders::plot_default_shader_handle())
    }

    fn specialize(_descriptor: &mut RenderPipelineDescriptor, _key: UiMaterialKey<Self>) {}
}

/// Plot `UiMaterial`
///
/// Points are packed into a `PlotPointsUniform` uniform at `@group(1) @binding(1)`.
#[derive(Asset, AsBindGroup, TypePath, Clone)]
pub struct PlotUiMaterialTexture {
    #[uniform(0)]
    pub params: PlotUniform,
    #[uniform(1)]
    pub points: PlotPointsUniform,
}

impl UiMaterial for PlotUiMaterialTexture {
    fn fragment_shader() -> ShaderRef {
        ShaderRef::Handle(shaders::plot_texture_shader_handle())
    }

    fn specialize(_descriptor: &mut RenderPipelineDescriptor, _key: UiMaterialKey<Self>) {}
}

// TODO: I'm copypastaing a lot of crap between wesl and rust. I should yeet
// this into build.rs and have a shared consts file betwixt ye olde rust lande
// and ye weirde gpu lande and the source of truth is always rust.
//
// SLUG_TEX_WIDTH is defined in build.rs and generated into constants.rs,
// which is included below. This keeps it in sync with the shader automatically.

// TODO: All this crap too is a good candidate for a refactor to keep the params
// et al in sync.
/// SlugParams uniform 16 bytes UiMaterial-only junk in the trunk to mimic bevy ui.
///
/// Layout must match `SlugParams` in lib/slug/types.wesl, future mitch combine stop lazy:
///   0   node_size    : `vec2<f32>`  - resolved node pixel size; used by ui_text.wesl
///                                     to convert in.uv -> pixel coordinates before
///                                     calling slugtext().
///   8   layout_flags : u32          - 4-bit packed Layout bitfield (see layout.rs).
///                                     Passed directly to slugtext() in ui_text.wesl.
///   12  alpha_discard : f32 - coverage threshold below which the 3D fragment
///                             shader discards the pixel and skips the depth write.
///                             Defaults to 0.01 (preserves smooth sub-pixel AA).
///                             Ignored by 2D/UI shader paths.
#[derive(Clone, Copy, ShaderType, bytemuck::Pod, bytemuck::Zeroable)]
#[repr(C)]
pub struct SlugParams {
    pub node_size: Vec2,
    pub layout_flags: u32,
    pub alpha_discard: f32,
}

impl Default for SlugParams {
    fn default() -> Self {
        SlugParams {
            node_size: Vec2::ZERO,
            layout_flags: 0,
            alpha_discard: 0.01,
        }
    }
}

/// Per-run descriptor uploaded once per shaped text string.
///
/// 16 bytes = 1 x `vec4<f32>` fits in a single rgba32float texel on webgl.
///
/// Layout must match `SlugRunDesc` in lib/slug/types.wesl:
///   0   natural_advance : f32  - total advance width of the run at font_size (px)
///   4   natural_height  : f32  - (ascender − descender) x scale at font_size (px)
///   8   glyph_offset    : u32  - first index into glyph_layout[] for this run
///   12  glyph_count     : u32  - number of SlugGlyphLayout entries in this run
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SlugRunDesc {
    pub natural_advance: f32,
    pub natural_height: f32,
    pub glyph_offset: u32,
    pub glyph_count: u32,
}

/// Packed atlas layout produced by `SlugAtlas::build_frame_atlas`.
/// Stores byte offsets and sizes into a single contiguous buffer on native,
/// or the dimensions needed to build webgl data textures for effing webgl's bs.
#[derive(Clone, Default, Debug)]
pub struct SlugAtlasLayout {
    /// Raw curves bytes, 24 bytes per curve, no padding.
    pub curves_data: Vec<u8>,
    /// Raw curve index bytes 4 bytes per u32.
    pub curve_indices_data: Vec<u8>,
    /// Raw glyph bytes 80 bytes per SlugGlyph struct.
    pub glyphs_data: Vec<u8>,
}

impl SlugAtlasLayout {
    /// Total bytes when packed sequentially.
    pub fn total_bytes(&self) -> usize {
        self.curves_data.len() + self.curve_indices_data.len() + self.glyphs_data.len()
    }

    /// Assert that the data fits within the for now 2048x2048 webgl texture
    /// limit chosen out of my ass to be roughly big enough for all JOYO kanji
    /// and ascii by my swag. I never tested it to find out how complex of
    /// curves they all had though. If not this is a fatal panic.
    pub fn assert_fits_webgl_textures(&self) {
        let max_texels = (SLUG_TEX_WIDTH * SLUG_TEX_WIDTH) as usize;

        // Curves are represented as 2 rgba32float texels per 24-byte curve.
        let curve_count = self.curves_data.len() / 24;
        let curve_texels = curve_count * 2;
        assert!(
            curve_texels <= max_texels,
            "SlugAtlasLayout: {} curves require ~{} texels but webgl texture \
             size is capped to {} ({}x{}). Reduce the visible glyph set or recompile with \
             SLUG_TEX_WIDTH. Or make this dynamic finally future mitch.",
            curve_count,
            curve_texels,
            max_texels,
            SLUG_TEX_WIDTH,
            SLUG_TEX_WIDTH
        );

        // Curve indices are 4 u32s per rgba32uint texel.
        let index_count = self.curve_indices_data.len() / 4;
        let index_texels = index_count.div_ceil(4);
        assert!(
            index_texels <= max_texels,
            "SlugAtlasLayout: {} curve indices require {} texels but webgl texture \
             size is {}. Reduce the visible glyph set or increase SLUG_TEX_WIDTH. \
             Or make this dynamic finally future mitch.",
            index_count,
            index_texels,
            max_texels
        );

        // Glyphs are 5 rgba32uint texels per 80-byte SlugGlyph.
        let glyph_count = self.glyphs_data.len() / 80;
        let glyph_texels = glyph_count * 5;
        assert!(
            glyph_texels <= max_texels,
            "SlugAtlasLayout: {} glyphs require {} texels but webgl texture \
             size is {}. Reduce the charset or increase SLUG_TEX_WIDTH. \
             Or make this dynamic finally future mitch.",
            glyph_count,
            glyph_texels,
            max_texels
        );
    }

    /// Build a `texture_2d<f32>` rgba32float Image for the bezier curves data.
    /// Each curve occupies 2 texels: (p0.x,p0.y,p1.x,p1.y) and (p2.x,p2.y,0,0).
    pub fn curves_image(&self) -> bevy::prelude::Image {
        use bevy::asset::RenderAssetUsages;
        use bevy::prelude::Image;
        use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};

        let curve_count = self.curves_data.len() / 24;
        let texel_count = curve_count * 2;
        let width = SLUG_TEX_WIDTH;
        let height = ((texel_count as u32).div_ceil(width)).max(1);

        let total_texels = (width * height) as usize;

        let mut pixels = vec![0u8; total_texels * 16];

        for (ci, chunk) in self.curves_data.chunks_exact(24).enumerate() {
            let base = ci * 2 * 16;
            pixels[base..base + 16].copy_from_slice(&chunk[0..16]);
            pixels[base + 16..base + 24].copy_from_slice(&chunk[16..24]);
        }

        Image::new(
            Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
            TextureDimension::D2,
            pixels,
            TextureFormat::Rgba32Float,
            RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
        )
    }

    /// Build a `texture_2d<u32>` rgba32uint Image for the curve indices.
    /// 4 u32s are packed per texel.
    pub fn curve_indices_image(&self) -> bevy::prelude::Image {
        use bevy::asset::RenderAssetUsages;
        use bevy::prelude::Image;
        use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};

        let index_count = self.curve_indices_data.len() / 4;
        let texel_count = index_count.div_ceil(4);
        let width = SLUG_TEX_WIDTH;
        let height = ((texel_count as u32).div_ceil(width)).max(1);

        let total_bytes = (width * height) as usize * 16;
        let mut pixels = vec![0u8; total_bytes];
        pixels[..self.curve_indices_data.len()].copy_from_slice(&self.curve_indices_data);

        Image::new(
            Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
            TextureDimension::D2,
            pixels,
            TextureFormat::Rgba32Uint,
            RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
        )
    }

    /// Build a `texture_2d<u32>` rgba32uint Image for the glyph data.
    /// Each SlugGlyph is 80 bytes = 5 x `vec4<u32>` that occupies 5 texels.
    pub fn glyphs_image(&self) -> bevy::prelude::Image {
        use bevy::asset::RenderAssetUsages;
        use bevy::prelude::Image;
        use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};

        let glyph_count = self.glyphs_data.len() / 80;
        let texel_count = glyph_count * 5;
        let width = SLUG_TEX_WIDTH;
        let height = ((texel_count as u32).div_ceil(width)).max(1);

        let total_bytes = (width * height) as usize * 16;
        let mut pixels = vec![0u8; total_bytes];
        pixels[..self.glyphs_data.len()].copy_from_slice(&self.glyphs_data);

        Image::new(
            Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
            TextureDimension::D2,
            pixels,
            TextureFormat::Rgba32Uint,
            RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
        )
    }
}

/// Build a `texture_2d<f32>` rgba32float Image for a single `SlugRunDesc`.
///
/// Layout: one texel = `(natural_advance, natural_height, glyph_offset as f32,
/// glyph_count as f32)`. Matches `get_run()` in the texture-path shader.
pub fn build_runs_image(run: &SlugRunDesc) -> bevy::prelude::Image {
    use bevy::asset::RenderAssetUsages;
    use bevy::prelude::Image;
    use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};
    use bytemuck::cast_slice;

    let floats: [f32; 4] = [
        run.natural_advance,
        run.natural_height,
        run.glyph_offset as f32,
        run.glyph_count as f32,
    ];
    // MAIN_WORLD | RENDER_WORLD Bevy must keep a CPU copy so it can re-upload
    // after a pipeline reset or render-world rebuild. RENDER_WORLD-only images
    // are one-shot and disappear on the next frame/ecs tick.
    Image::new(
        Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        },
        TextureDimension::D2,
        cast_slice::<f32, u8>(&floats).to_vec(),
        TextureFormat::Rgba32Float,
        RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
    )
}

/// Build a `texture_2d<f32>` rgba32float Image for a slice of `SlugGlyphLayout`.
///
/// Layout: 3 texels per entry:
///   texel 0 - `screen_rect` (vec4f)
///   texel 1 - `em_rect`     (vec4f)
///   texel 2 - `glyph_index as f32, 0, 0, 0`
///
/// Matches `get_glyph_layout()` in the texture-path shader.
pub fn build_glyph_layout_image(layouts: &[slug::SlugGlyphLayout]) -> bevy::prelude::Image {
    use bevy::asset::RenderAssetUsages;
    use bevy::prelude::Image;
    use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};
    use bytemuck::cast_slice;

    let count = layouts.len();
    let texels = count * 3;
    let width = SLUG_TEX_WIDTH;
    let height = ((texels as u32).div_ceil(width)).max(1);
    let total = (width * height) as usize * 4;
    let mut floats = vec![0.0f32; total];
    for (i, g) in layouts.iter().enumerate() {
        let base = i * 3 * 4;
        floats[base..base + 4].copy_from_slice(&g.screen_rect);
        floats[base + 4..base + 8].copy_from_slice(&g.em_rect);
        floats[base + 8] = g.glyph_index as f32;
    }
    Image::new(
        Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        },
        TextureDimension::D2,
        cast_slice::<f32, u8>(&floats).to_vec(),
        TextureFormat::Rgba32Float,
        RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
    )
}

/// Marker component for entities that are managed slug text nodes.
#[derive(Component)]
pub struct SlugText;

// SlugMaterial params upload pipeline, cause this is all more complex that it
// probably needs to be but I'm still learning to abuse the ECS with custom shaders.

/// Per `atlas_buffer` packed bytes for the native SlugMaterial upload pipeline.
///
/// Keyed by `AssetId` of the pre-allocated `atlas_buffer`
/// `ShaderBuffer`. Set by `upload_layout_native` when the new atlas data
/// fits within the existing buffer capacity; the render-world system
/// `upload_slug_atlas` calls `write_buffer` to push the bytes to the GPU. When
/// capacity is exceeded a new buffer is allocated which causes a new Bind Group
/// but thats hard to avoid, in which case no entry is added.
#[cfg(not(feature = "webgl"))]
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct SlugAtlasUploadMap {
    pub entries: std::collections::HashMap<bevy::asset::AssetId<ShaderBuffer>, Vec<u8>>,
}

/// Render-world system to write atlas bytes into `atlas_buffer` SSBs.
#[cfg(not(feature = "webgl"))]
pub fn upload_slug_atlas(
    upload_map: Res<SlugAtlasUploadMap>,
    gpu_bufs: Res<RenderAssets<GpuShaderBuffer>>,
    render_queue: Res<RenderQueue>,
) {
    for (id, bytes) in &upload_map.entries {
        if let Some(gpu_buf) = gpu_bufs.get(*id) {
            render_queue.write_buffer(&gpu_buf.buffer, 0, bytes);
        }
    }
}

/// Per `draw_buffer` packed bytes for the native SlugMaterial upload pipeline.
#[cfg(not(feature = "webgl"))]
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct SlugDrawUploadMap {
    pub entries: std::collections::HashMap<bevy::asset::AssetId<ShaderBuffer>, Vec<u8>>,
}

/// Render-world system: write draw bytes to pre-allocated `draw_buffer` SSBs.
#[cfg(not(feature = "webgl"))]
pub fn upload_slug_draw(
    upload_map: Res<SlugDrawUploadMap>,
    gpu_bufs: Res<RenderAssets<GpuShaderBuffer>>,
    render_queue: Res<RenderQueue>,
) {
    for (id, bytes) in &upload_map.entries {
        if let Some(gpu_buf) = gpu_bufs.get(*id) {
            render_queue.write_buffer(&gpu_buf.buffer, 0, bytes);
        }
    }
}

/// Per `params_buf` payload for the native SlugMaterial upload pipeline.
///
/// Each entry maps the `AssetId` of a pre-allocated `params_buf`
/// `ShaderBuffer` to the 96 bytes that should be written into it this frame
///
#[cfg(not(feature = "webgl"))]
#[derive(Resource, Clone, Default, ExtractResource)]
pub struct SlugParamsUploadMap {
    pub entries: std::collections::HashMap<bevy::asset::AssetId<ShaderBuffer>, [u8; 96]>,
}

/// Render-world system for every entry in `SlugParamsUploadMap`, write the
/// uniform into the entity's pre-allocated `params_buf` SSB.
#[cfg(not(feature = "webgl"))]
pub fn upload_slug_params(
    upload_map: Res<SlugParamsUploadMap>,
    gpu_bufs: Res<RenderAssets<GpuShaderBuffer>>,
    render_queue: Res<RenderQueue>,
) {
    for (id, bytes) in &upload_map.entries {
        if let Some(gpu_buf) = gpu_bufs.get(*id) {
            render_queue.write_buffer(&gpu_buf.buffer, 0, bytes);
        }
    }
}

const DISPLAY_RANGE_ALPHA: f32 = 0.04;

/// Minimum Y-axis range exposed to the shader in whatever units bevy reported
/// for fps.
///
/// Prevents the sparkline from zooming into tiny sub-fps variations and making
/// a steady ~60 ish fps signal oscillate weirdly. It oscillates weirdly
/// differently now but I don't care its a winter me task to fix.
const DISPLAY_MIN_RANGE: f32 = 15.0;

#[derive(Resource)]
pub struct StatsOverlayData {
    /// Raw fps history, latest at the tail end.
    history: Vec<f32>,
    /// True after the first fps > 0.0 has been pushed for history.
    primed: bool,
    /// EMA-smoothed lower bound of the displayed Y range.
    ema_min: f32,
    /// EMA-smoothed upper bound of the displayed Y range.
    ema_max: f32,
}

impl Default for StatsOverlayData {
    fn default() -> Self {
        Self::new()
    }
}

impl StatsOverlayData {
    pub fn new() -> Self {
        Self {
            history: Vec::with_capacity(STATS_OVERLAY_HISTORY_SIZE),
            primed: false,
            ema_min: 0.0,
            ema_max: 0.0,
        }
    }

    // TODO: This could use some noodling, bevy reports some weird af numbers
    // sometimes that make zero sense like 400fps for a 120fps render hardware
    // chain.

    /// Push the current FPS value into the stored history.
    ///
    /// Values below 0.0???? are silently dropped before and after
    /// initialization so stale diagnostic readings during startup never appear
    /// in the plot.
    ///
    /// After each push the EMA display range is updated:
    /// - expands instantly when the actual recorded range widens
    /// - contracts more slowly via the time constant of about 2.5 s when it narrows
    // Its a bit jank still but I can fiddle with it later.
    pub fn push_fps(&mut self, fps: f32) {
        if fps <= 0.0 {
            return;
        }
        if !self.primed {
            self.history.resize(STATS_OVERLAY_HISTORY_SIZE, fps);
            self.primed = true;
            self.ema_min = fps;
            self.ema_max = fps;
            return;
        }
        if self.history.len() >= STATS_OVERLAY_HISTORY_SIZE {
            self.history.remove(0);
        }
        self.history.push(fps);

        // Compute the actual min/max from the averaged 256-point windows.
        let pts = self.averaged_points();
        let actual_min = pts.iter().copied().fold(f32::INFINITY, f32::min).max(0.0);
        let actual_max = pts
            .iter()
            .copied()
            .fold(f32::NEG_INFINITY, f32::max)
            .max(0.0);

        // Expand instantly and contract slowly via asymmetric EMA.
        self.ema_max = if actual_max > self.ema_max {
            actual_max
        } else {
            DISPLAY_RANGE_ALPHA * actual_max + (1.0 - DISPLAY_RANGE_ALPHA) * self.ema_max
        };
        self.ema_min = if actual_min < self.ema_min {
            actual_min
        } else {
            DISPLAY_RANGE_ALPHA * actual_min + (1.0 - DISPLAY_RANGE_ALPHA) * self.ema_min
        };
    }

    /// Return an array of 256 TODO wat was the const again? averaged FPS values.
    ///
    /// The history is divided into 256 chunks of 10 samples each so each chunk
    /// is averaged into a single `f32` sent to the shader to plot. If the
    /// history has fewer than `STATS_OVERLAY_HISTORY_SIZE` entries aka before
    /// the first push or at startup, the result is all zeros.
    pub fn averaged_points(&self) -> [f32; STATS_OVERLAY_POINT_COUNT] {
        let mut out = [0.0f32; STATS_OVERLAY_POINT_COUNT];
        if self.history.len() < STATS_OVERLAY_HISTORY_SIZE {
            return out;
        }
        let chunk = STATS_OVERLAY_HISTORY_SIZE / STATS_OVERLAY_POINT_COUNT; // = 10
        for (i, slot) in out.iter_mut().enumerate() {
            let start = i * chunk;
            let end = (start + chunk).min(self.history.len());
            if start >= end {
                break;
            }
            let sum: f32 = self.history[start..end].iter().sum();
            *slot = sum / (end - start) as f32;
        }
        out
    }

    /// Return the most recently pushed FPS value or 0.0 if nothing has been pushed.
    pub fn latest_fps(&self) -> f32 {
        self.history.last().copied().unwrap_or(0.0)
    }

    /// Return the raw minimum of the current 256 averaged points.
    pub fn min_fps(&self) -> f32 {
        self.averaged_points()
            .iter()
            .copied()
            .fold(f32::INFINITY, f32::min)
            .max(0.0)
    }

    /// Return the raw maximum of the current 256 averaged points.
    pub fn max_fps(&self) -> f32 {
        self.averaged_points()
            .iter()
            .copied()
            .fold(f32::NEG_INFINITY, f32::max)
            .max(0.0)
    }

    /// Return the display minimum for the shader Y axis.
    ///
    /// Applies the EMA-smoothed lower bound and the minimum range floor so
    /// the sparkline Y axis contracts slowly and never zooms weirdly into sub-fps
    /// noise which was pissing me off.
    pub fn display_min_fps(&self) -> f32 {
        let center = (self.ema_min + self.ema_max) * 0.5;
        let half = ((self.ema_max - self.ema_min) * 0.5).max(DISPLAY_MIN_RANGE * 0.5);
        (center - half).max(0.0)
    }

    /// Return the display maximum for the shader Y axis.
    pub fn display_max_fps(&self) -> f32 {
        let center = (self.ema_min + self.ema_max) * 0.5;
        let half = ((self.ema_max - self.ema_min) * 0.5).max(DISPLAY_MIN_RANGE * 0.5);
        center + half
    }

    /// Encode the 256 averaged FPS values as LE f32 bytes for `write_buffer`.
    pub fn fps_points_bytes(&self) -> Vec<u8> {
        self.averaged_points()
            .iter()
            .flat_map(|f| f.to_le_bytes())
            .collect()
    }
}

#[cfg(test)]
mod stats_overlay_tests {
    use super::*;

    #[test]
    fn prime_fills_history_with_first_fps() {
        let mut d = StatsOverlayData::new();
        d.push_fps(45.0);
        assert_eq!(d.history.len(), STATS_OVERLAY_HISTORY_SIZE);
        assert!(d.history.iter().all(|&v| (v - 45.0).abs() < 1e-6));
    }

    #[test]
    fn no_prime_on_zero_fps() {
        let mut d = StatsOverlayData::new();
        d.push_fps(0.0);
        assert!(!d.primed, "zero fps must not prime the history");
        assert!(d.history.is_empty());
    }

    #[test]
    fn zero_fps_dropped_after_priming() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0); // prime
        let len_before = d.history.len();
        d.push_fps(0.0); // must be ignored
        assert_eq!(
            d.history.len(),
            len_before,
            "zero must not be pushed after prime"
        );
    }

    #[test]
    fn negative_fps_dropped() {
        let mut d = StatsOverlayData::new();
        d.push_fps(-1.0);
        assert!(!d.primed, "negative fps must not prime");
        d.push_fps(60.0);
        let len = d.history.len();
        d.push_fps(-5.0);
        assert_eq!(
            d.history.len(),
            len,
            "negative fps must not be pushed after prime"
        );
    }

    #[test]
    fn history_caps_at_history_size() {
        let mut d = StatsOverlayData::new();
        for i in 0..STATS_OVERLAY_HISTORY_SIZE + 100 {
            d.push_fps(i as f32 + 1.0);
        }
        assert_eq!(d.history.len(), STATS_OVERLAY_HISTORY_SIZE);
    }

    #[test]
    fn latest_fps_returns_last_pushed() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        d.push_fps(72.5);
        assert!((d.latest_fps() - 72.5).abs() < 1e-6);
    }

    #[test]
    fn averaged_points_all_same_when_constant_fps() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        for _ in 0..STATS_OVERLAY_HISTORY_SIZE {
            d.push_fps(60.0);
        }
        let pts = d.averaged_points();
        for (i, &v) in pts.iter().enumerate() {
            assert!((v - 60.0).abs() < 1e-4, "point {i} expected ~60.0, got {v}");
        }
    }

    #[test]
    fn averaged_points_returns_zeros_before_prime() {
        let d = StatsOverlayData::new();
        let pts = d.averaged_points();
        assert!(pts.iter().all(|&v| v == 0.0), "before prime all zeros");
    }

    #[test]
    fn fps_points_bytes_length() {
        let d = StatsOverlayData::new();
        assert_eq!(
            d.fps_points_bytes().len(),
            STATS_OVERLAY_POINT_COUNT * 4,
            "must be exactly 256 * 4 = 1024 bytes"
        );
    }

    #[test]
    fn min_max_fps_after_prime() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        let min = d.min_fps();
        let max = d.max_fps();
        assert!(
            (min - 60.0).abs() < 1e-4,
            "min_fps expected ~60.0, got {min}"
        );
        assert!(
            (max - 60.0).abs() < 1e-4,
            "max_fps expected ~60.0, got {max}"
        );
    }

    #[test]
    fn ema_seeded_on_prime() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        assert!(
            (d.ema_min - 60.0).abs() < 1e-4,
            "ema_min seeded at prime value"
        );
        assert!(
            (d.ema_max - 60.0).abs() < 1e-4,
            "ema_max seeded at prime value"
        );
    }

    #[test]
    fn display_range_has_minimum_floor() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        let lo = d.display_min_fps();
        let hi = d.display_max_fps();
        assert!(
            hi - lo >= DISPLAY_MIN_RANGE - 1e-4,
            "display range must be at least {DISPLAY_MIN_RANGE}, got {}",
            hi - lo
        );
        assert!(
            (lo + hi) / 2.0 - 60.0 < 1e-4,
            "display range must be centered on ~60, center={}",
            (lo + hi) / 2.0
        );
    }

    #[test]
    fn display_max_expands_instantly_on_spike() {
        let mut d = StatsOverlayData::new();
        d.push_fps(60.0);
        for _ in 0..STATS_OVERLAY_HISTORY_SIZE {
            d.push_fps(120.0);
        }
        assert!(
            d.display_max_fps() >= 119.0,
            "display max must track spikes up, got {}",
            d.display_max_fps()
        );
    }

    #[test]
    fn display_min_never_negative() {
        let mut d = StatsOverlayData::new();
        d.push_fps(5.0);
        assert!(
            d.display_min_fps() >= 0.0,
            "display_min must be non-negative, got {}",
            d.display_min_fps()
        );
    }

    #[test]
    fn overlay_point_count_is_256() {
        assert_eq!(STATS_OVERLAY_POINT_COUNT, 256);
    }

    #[test]
    fn overlay_history_size_is_2560() {
        assert_eq!(STATS_OVERLAY_HISTORY_SIZE, 2560);
    }

    #[test]
    fn history_size_is_10x_point_count() {
        assert_eq!(STATS_OVERLAY_HISTORY_SIZE, STATS_OVERLAY_POINT_COUNT * 10);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(feature = "webgl")]
    fn plot_points_uniform_webgl_alignment() {
        use std::mem::size_of;
        assert_eq!(
            size_of::<PlotPointsUniform>() % 16,
            0,
            "PlotPointsUniform must be a multiple of 16 bytes for webgl got {} bytes",
            size_of::<PlotPointsUniform>()
        );
    }

    #[test]
    fn slug_params_is_16_bytes() {
        assert_eq!(
            std::mem::size_of::<SlugParams>(),
            16,
            "SlugParams must be exactly 16 bytes (node_size vec2 + 8 bytes pad)"
        );
    }

    #[test]
    fn slug_run_desc_is_16_bytes() {
        assert_eq!(
            std::mem::size_of::<SlugRunDesc>(),
            16,
            "SlugRunDesc must be exactly 16 bytes (1 x vec4<f32>) for webgl texel packing"
        );
    }

    #[test]
    // TODO: LEAK [   0.229s] flan tests::max_plot_points_constant
    // I'm not sure this will survive a refactor into bevy rendering.
    fn max_plot_points_constant() {
        assert_eq!(MAX_PLOT_POINTS, 512);
    }
}
