[package]
name = "shaders"
edition.workspace = true
license.workspace = true
version.workspace = true

# `render` feature enables the headless wgpu test harness used for unit testing
# render output so I at least know if I broke what I expect stuff to look like.

[features]
default = ["render"]
webgl = []
render = [
  "dep:wgpu",
  "dep:image",
  "dep:image-compare",
  "dep:pollster",
  "dep:wesl",
]

[dependencies]
bevy = { version = "~0.18.1", features = ["shader_format_wesl"] }
# Force naga/termcolor on here or we can't compile tests.
naga.workspace = true
# wgpu forced to v26 to match bevy wgpu
wgpu = { version = "26", optional = true, features = [
  "metal",
  "vulkan",
  "dx12",
] }
image = { version = "0.25", optional = true, default-features = false, features = [
  "png",
] }
image-compare = { version = "0.5", optional = true }
pollster = { version = "0.4", optional = true }
wesl = { version = "~0.3.2", optional = true }

[dev-dependencies]
bytemuck = { version = "1", features = ["derive"] }

[[test]]
name = "shader_2d"
required-features = ["render"]

[[test]]
name = "shader_fullscreen"
required-features = ["render"]
