[package]
name = "mitchty"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mitchty"
path = "src/main.rs"

# wasm/web builds should use webgl2 for now, webgpu is slow af in every browser
# aka 4fps vs like 120 frame limited with webgl2
#
# That or I didn't enable webgpu right in safari/chrome/firefox I dunno.
#
# I'll stick to webgl until bevy nukes support for it in a year or two according
# to discord chatter.
[features]
default = ["egui"]
webgl = ["bevy/webgl2", "flan/webgl"]
webgpu = ["bevy/webgpu"]
egui = ["dep:bevy_egui"]
feathers = []

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
  "ui",
  "3d",
  "experimental_bevy_feathers",
] }

rand.workspace = true
clap = { version = "~4.5.60", features = ["derive"] }
bevy_fontmesh = "~0.3"
bevy_egui = { version = "~0.39.1", optional = true }
bevy_pretty_text = "~0.4"
markdown = "1.0.0"
flan = { path = "../flan" }
shaders = { path = "../shaders" }

# console_error_panic_hook is here so that the web console for js? or whatever
# dumps out backtraces.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
polars = { version = "~0.53", default-features = false, features = ["lazy"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "~0.1.7"
# FUTURE MITCH: this is a dependency OF rand, and without the wasm_js feature
# crap don't work. Stop uncommenting things dammit trust past mitch.
getrandom.workspace = true
# Note: polars on wasm is.... not fun, feature gates need to constrain it so it
# runs wicked slower than native
polars = { version = "~0.53", default-features = false }
# TODO: browser detection needed at some point? I actually caught a
# bevy_feathers bug and wasn't sure if it was safari or not. Here for future me
# to remember to use this if needed.
#web-sys = { version = "~0.3", features = ["Navigator", "Window"] }
